/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_analytics_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Me */
        get: operations["read_me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Checkout */
        post: operations["checkout_payments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pending */
        get: operations["pending_payments_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{reference}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify */
        post: operations["verify_payments__reference__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plans */
        get: operations["plans_plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/savings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Savings Report */
        post: operations["savings_report_reports_savings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Statements */
        get: operations["list_statements_statements_get"];
        put?: never;
        /**
         * Upload
         * @description Parses, categorizes and stores a CSV or PDF statement.
         */
        post: operations["upload_statements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statements/{statement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_statements__statement_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["list_transactions_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_statements_post */
        Body_upload_statements_post: {
            /** File */
            file: string;
        };
        /** CategoryPoint */
        CategoryPoint: {
            /** Category */
            category: string;
            /** Count */
            count: number;
            /** Total Minor */
            total_minor: number;
        };
        /** ChatIn */
        ChatIn: {
            /** Message */
            message: string;
        };
        /** CheckoutIn */
        CheckoutIn: {
            /**
             * Currency
             * @default NGN
             * @enum {string}
             */
            currency: "NGN" | "USD";
            /**
             * Plan Id
             * @enum {string}
             */
            plan_id: "pro_month" | "pro_year";
        };
        /** CheckoutOut */
        CheckoutOut: {
            /** Authorization Url */
            authorization_url: string;
            /** Reference */
            reference: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MeOut */
        MeOut: {
            /** Email */
            email: string;
            /** Full Name */
            full_name: string | null;
            /** Id */
            id: string;
            /** Is Pro */
            is_pro: boolean;
            /** Pro Until */
            pro_until: string | null;
            /** Upload Limit */
            upload_limit: number | null;
            /** Uploads This Month */
            uploads_this_month: number;
        };
        /** MonthPoint */
        MonthPoint: {
            /** Income Minor */
            income_minor: number;
            /** Month */
            month: string;
            /** Spent Minor */
            spent_minor: number;
        };
        /** Opportunity */
        Opportunity: {
            /** Description */
            description: string;
            /** Monthly Minor */
            monthly_minor: number;
            /** Saving Minor */
            saving_minor: number;
            /** Target */
            target: string;
            /** Title */
            title: string;
        };
        /** PaymentStatus */
        PaymentStatus: {
            /** Pro Until */
            pro_until?: string | null;
            /** Reference */
            reference: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "paid" | "failed";
        };
        /** PlanOut */
        PlanOut: {
            /** Days */
            days: number;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Prices Minor */
            prices_minor: {
                [key: string]: number;
            };
        };
        /** Report */
        Report: {
            /** Currency */
            currency: string;
            /** Opportunities */
            opportunities: components["schemas"]["Opportunity"][];
            /** Summary */
            summary: string;
            /** Total Saving Minor */
            total_saving_minor: number;
            /** Window Days */
            window_days: number;
        };
        /** StatementOut */
        StatementOut: {
            /**
             * Anomaly Count
             * @default 0
             */
            anomaly_count: number;
            /** Currency */
            currency: string;
            /** Filename */
            filename: string;
            /** Id */
            id: string;
            /** Period End */
            period_end: string | null;
            /** Period Start */
            period_start: string | null;
            /** Row Count */
            row_count: number;
        };
        /** Summary */
        Summary: {
            /** Anomaly Count */
            anomaly_count: number;
            /** By Category */
            by_category: components["schemas"]["CategoryPoint"][];
            /** Currencies */
            currencies: string[];
            /** Currency */
            currency: string | null;
            /** Income Minor */
            income_minor: number;
            /** Month */
            month: string | null;
            /** Monthly */
            monthly: components["schemas"]["MonthPoint"][];
            /** Previous Spent Minor */
            previous_spent_minor: number | null;
            /** Spent Minor */
            spent_minor: number;
            /** Transaction Count */
            transaction_count: number;
        };
        /** TransactionOut */
        TransactionOut: {
            /** Amount Minor */
            amount_minor: number;
            /** Category */
            category: string;
            /** Currency */
            currency: string;
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Is Anomaly */
            is_anomaly: boolean;
            /** Merchant */
            merchant: string | null;
            /**
             * Transaction Date
             * Format: date
             */
            transaction_date: string;
        };
        /** TransactionPage */
        TransactionPage: {
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
            /** Transactions */
            transactions: components["schemas"]["TransactionOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    summary_analytics_summary_get: {
        parameters: {
            query?: {
                /** @description YYYY-MM; defaults to the latest month */
                month?: string | null;
                currency?: string | null;
                months?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    checkout_payments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pending_payments_pending_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    verify_payments__reference__verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reference: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plans_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"][];
                };
            };
        };
    };
    savings_report_reports_savings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
        };
    };
    list_statements_statements_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementOut"][];
                };
            };
        };
    };
    upload_statements_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_statements_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_statements__statement_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                statement_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_transactions_transactions_get: {
        parameters: {
            query?: {
                /** @description YYYY-MM */
                month?: string | null;
                category?: string | null;
                search?: string | null;
                flagged?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
